# Generated by Django 3.1.5 on 2021-01-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('tipo_id', models.CharField(choices=[('Cédula Ciudadanía', 'Cedula Ciudadanía'), ('Pasaporte', 'Pasaporte'), ('Cédula de Extranjería', 'Cédula de Extranjería')], default='Cedula', max_length=25, verbose_name='Tipo Id')),
                ('identificacion', models.CharField(max_length=30, unique=True, verbose_name='Identificación')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('whatsapp', models.CharField(max_length=15, verbose_name='WSP')),
                ('correo', models.CharField(max_length=150, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
