# Generated by Django 3.1.5 on 2021-01-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=150, unique=True, verbose_name='NIT')),
                ('pais', models.CharField(max_length=150, verbose_name='Pais')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefono')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='WSP')),
                ('correo', models.CharField(max_length=150, unique=True, verbose_name='Correo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clientEmp/%Y/%m/%d', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'ClienteEmp',
                'verbose_name_plural': 'ClientesEmp',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='WSP'),
        ),
    ]
