# Generated by Django 3.1.5 on 2021-01-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210120_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telefono',
            field=models.CharField(blank=True, default='---', max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(blank=True, default='---', max_length=15, null=True, verbose_name='WSP'),
        ),
    ]
