# Generated by Django 3.1.5 on 2021-01-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20210120_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='correo',
            field=models.CharField(max_length=150, unique=True, verbose_name='Correo'),
        ),
    ]
