# Generated by Django 3.1.5 on 2021-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210122_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemp',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='clientEmp/%Y/%m/%d', verbose_name='Logo', width_field=200),
        ),
    ]
