# Generated by Django 3.1.5 on 2021-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210123_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clientEmp/%Y/%m/%d', verbose_name='Logo'),
        ),
    ]
